version: 2

models:

  - name: stg_candidates
    columns:
      - name: property_id
        tests:
          - unique :
              severity: warn
          - not_null
          - relationships:
              to: ref('stg_scores')
              field: property_id
              severity: warn
      - name: district
        tests:
          - relationships:
              to: ref('stg_edinburgh_districts')
              field: postcode_district
              severity: warn

  - name: stg_edinburgh_districts
    columns:
      - name: postcode_district
        tests:
          - unique
          - not_null

  - name: stg_scores
    columns:
      - name: property_id
        tests:
          - unique
          - not_null